library("testthat")

# Test for ass function
expect_error(IPIPANRcourseHomework::ass ("a", "B"))
expect_error(IPIPANRcourseHomework::ass2("a", "B"))
expect_error(IPIPANRcourseHomework::ass (c(2,3,4)))
expect_error(IPIPANRcourseHomework::ass2(c(2,3,4)))
expect_error(IPIPANRcourseHomework::ass (-2))
expect_error(IPIPANRcourseHomework::ass2(-2))
expect_error(IPIPANRcourseHomework::ass (0))
expect_error(IPIPANRcourseHomework::ass2(0))

expect_equal(IPIPANRcourseHomework::ass(1), IPIPANRcourseHomework::ass2(1))
expect_equal(IPIPANRcourseHomework::ass(2), IPIPANRcourseHomework::ass2(2))
expect_equal(IPIPANRcourseHomework::ass(3), IPIPANRcourseHomework::ass2(3))
expect_equal(IPIPANRcourseHomework::ass(4), IPIPANRcourseHomework::ass2(4))

expect_equal(rowSums(IPIPANRcourseHomework::ass (1)), rep(1, 2))
expect_equal(rowSums(IPIPANRcourseHomework::ass2(1)), rep(1, 2))
expect_equal(rowSums(IPIPANRcourseHomework::ass (2)), rep(2, 6))
expect_equal(rowSums(IPIPANRcourseHomework::ass2(2)), rep(2, 6))
expect_equal(rowSums(IPIPANRcourseHomework::ass (3)), rep(3, 20))
expect_equal(rowSums(IPIPANRcourseHomework::ass2(3)), rep(3, 20))
expect_equal(rowSums(IPIPANRcourseHomework::ass (4)), rep(4, 70))
expect_equal(rowSums(IPIPANRcourseHomework::ass2(4)), rep(4, 70))

expect_equal(colSums(IPIPANRcourseHomework::ass (1)), rep(1, 2))
expect_equal(colSums(IPIPANRcourseHomework::ass2(1)), rep(1, 2))
expect_equal(colSums(IPIPANRcourseHomework::ass (2)), rep(3, 4))
expect_equal(colSums(IPIPANRcourseHomework::ass2(2)), rep(3, 4))
expect_equal(colSums(IPIPANRcourseHomework::ass (3)), rep(10, 6))
expect_equal(colSums(IPIPANRcourseHomework::ass2(3)), rep(10, 6))
expect_equal(colSums(IPIPANRcourseHomework::ass (4)), rep(35, 8))
expect_equal(colSums(IPIPANRcourseHomework::ass2(4)), rep(35, 8))
