// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mode
int mode(const IntegerVector x1);
RcppExport SEXP IPIPANRcourseHomework_mode(SEXP x1SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const IntegerVector >::type x1(x1SEXP);
    __result = Rcpp::wrap(mode(x1));
    return __result;
END_RCPP
}
// simplify2array2
SEXP simplify2array2(const List L, bool higher);
RcppExport SEXP IPIPANRcourseHomework_simplify2array2(SEXP LSEXP, SEXP higherSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const List >::type L(LSEXP);
    Rcpp::traits::input_parameter< bool >::type higher(higherSEXP);
    __result = Rcpp::wrap(simplify2array2(L, higher));
    return __result;
END_RCPP
}
// ass
NumericMatrix ass(int n);
RcppExport SEXP IPIPANRcourseHomework_ass(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    __result = Rcpp::wrap(ass(n));
    return __result;
END_RCPP
}
