# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Returns vector's mode.
#' @description This function calculates the most frequently
#' occurring value in an integer vector (mode).
#' If the mode is ambiguous returns the lowest mode.
#' Please note that "mode" overrides mode function
#' from base package.
#'
#' @param x1 - integer vector
#' @return - integer
#'
#' @export
mode <- function(x1) {
    .Call('IPIPANRcourseHomework_mode', PACKAGE = 'IPIPANRcourseHomework', x1)
}

#' @title Mimics built-in simplify2array function.
#' @description This function behaves as most similar
#' to simplify2array as possible.
#' If list contains vectors of length 1, returns vector.
#' If list contains vectors of the same length, returns matrix.
#' Otherwise returns not changed List.
#'
#' @param L - List of numeric vectors to convert
#' @param higher (optional) - not used in this implementation
#' @return - matrix, vector or list
#'
#' @export
simplify2array2 <- function(L, higher = TRUE) {
    .Call('IPIPANRcourseHomework_simplify2array2', PACKAGE = 'IPIPANRcourseHomework', L, higher)
}

#' @title Generates all possible assignments of survey participants.
#' @description This function generates all possible 0-1 assignment
#' vectors of 2n survey participants in such a way that
#' exactly n of them are assigned to group 0 (control)
#' and the other n ones are assigned to group 1 (treatment).
#'
#' @param n - single integer - number of participants
#' @return - matrix
#'
#' @export
ass <- function(n) {
    .Call('IPIPANRcourseHomework_ass', PACKAGE = 'IPIPANRcourseHomework', n)
}

